name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./frontend  # 关键修改
        run: npm install

      - name: Build project
        working-directory: ./frontend  # 关键修改
        run: npm run build

      - name: Zip dist folder
        working-directory: ./frontend  # 确保在frontend目录操作
        run: zip -r ../dist.zip dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-zip
          path: dist.zip
